version: "3.9"
services:
  checker:
    container_name: checker
    build: .
    entrypoint: wait-for postgres:5432 -- sh -c "npm install && npx prisma migrate dev && npm run start:dev"
    restart: always
    volumes:
      - .:/home/node/app
    ports:
      - 8001:3000
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - checker-network

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - checker-network

networks:
  checker-network:
    driver: bridge

volumes:
  postgres:
